In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle


In [4]:
dataset = pd.read_csv("Student_performance_data _.csv")

In [5]:
dataset

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0          1001   17       1          0                  2        19.833723   
1          1002   18       0          0                  1        15.408756   
2          1003   15       0          2                  3         4.210570   
3          1004   17       1          0                  3        10.028829   
4          1005   17       1          0                  2         4.672495   
...         ...  ...     ...        ...                ...              ...   
2387       3388   18       1          0                  3        10.680555   
2388       3389   17       0          0                  1         7.583217   
2389       3390   16       1          0                  2         6.805500   
2390       3391   16       1          1                  0        12.416653   
2391       3392   16       1          0                  2        17.819907   

      Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0            7         1                2                0       0      1   
1            0         0                1                0       0      0   
2           26         0                2                0       0      0   
3           14         0                3                1       0      0   
4           17         1                3                0       0      0   
...        ...       ...              ...              ...     ...    ...   
2387         2         0                4                1       0      0   
2388         4         1                4                0       1      0   
2389        20         0                2                0       0      0   
2390        17         0                2                0       1      1   
2391        13         0                2                0       0      0   

      Volunteering       GPA  GradeClass  
0                0  2.929196         2.0  
1                0  3.042915         1.0  
2                0  0.112602         4.0  
3                0  2.054218         3.0  
4                0  1.288061         4.0  
...            ...       ...         ...  
2387             0  3.455509         0.0  
2388             0  3.279150         4.0  
2389             1  1.142333         2.0  
2390             0  1.803297         1.0  
2391             1  2.140014         1.0  

[2392 rows x 15 columns]

In [6]:
dataset.drop(["GPA"],axis=1,inplace=True)

In [7]:
dataset.drop(["StudentID"],axis=1,inplace=True)

In [8]:
dataset.dtypes

Age                    int64
Gender                 int64
Ethnicity              int64
ParentalEducation      int64
StudyTimeWeekly      float64
Absences               int64
Tutoring               int64
ParentalSupport        int64
Extracurricular        int64
Sports                 int64
Music                  int64
Volunteering           int64
GradeClass           float64
dtype: object

In [9]:
dataset_x = dataset.iloc[:,:-1]
dataset_y = dataset.iloc[:,-1]

In [10]:
train_x,test_x,train_y,test_y = train_test_split(dataset_x,dataset_y,test_size=0.3,random_state=42)

In [11]:
classifier = RandomForestClassifier(n_estimators=150,random_state=42)

In [12]:
classifier.fit(train_x,train_y)

RandomForestClassifier(n_estimators=150, random_state=42)

In [13]:
y_pred = classifier.predict(test_x)

In [14]:
y_pred

array([4., 2., 4., 1., 4., 3., 4., 4., 3., 4., 2., 4., 2., 2., 2., 4., 4.,
       4., 4., 3., 3., 4., 4., 1., 4., 4., 4., 2., 4., 4., 4., 4., 2., 1.,
       4., 4., 2., 2., 0., 4., 2., 1., 4., 4., 4., 2., 2., 4., 2., 4., 2.,
       1., 4., 4., 4., 1., 3., 1., 4., 3., 4., 4., 3., 4., 4., 3., 1., 2.,
       4., 1., 1., 4., 1., 2., 4., 1., 4., 4., 4., 4., 4., 1., 3., 4., 4.,
       4., 0., 4., 4., 4., 2., 4., 4., 4., 4., 4., 1., 4., 4., 4., 4., 3.,
       4., 4., 4., 3., 2., 4., 4., 4., 4., 4., 1., 4., 4., 4., 3., 2., 4.,
       4., 4., 1., 1., 4., 4., 4., 3., 4., 4., 2., 4., 0., 2., 4., 4., 4.,
       3., 4., 4., 4., 3., 4., 1., 4., 1., 4., 4., 3., 2., 4., 2., 4., 1.,
       4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 2.,
       4., 1., 2., 4., 4., 3., 3., 4., 4., 4., 1., 4., 4., 1., 2., 1., 2.,
       4., 4., 4., 4., 3., 4., 4., 4., 4., 4., 2., 2., 2., 4., 2., 4., 3.,
       3., 3., 4., 1., 3., 4., 4., 4., 3., 2., 2., 4., 2., 2., 4., 1., 4.,
       2., 2., 4., 4., 4.

In [15]:
accuracy = accuracy_score(test_y, y_pred)
conf_matrix = confusion_matrix(test_y, y_pred)
class_report = classification_report(test_y, y_pred)

In [16]:
accuracy

0.7061281337047354

In [17]:
test_y

1004    4.0
196     1.0
2342    2.0
1708    0.0
435     4.0
       ... 
1626    4.0
32      4.0
952     4.0
787     2.0
2149    4.0
Name: GradeClass, Length: 718, dtype: float64

In [18]:
# DOING THE PREDICTIONS WITH TEST DATA
import numpy as np
classifier.predict(np.array(test_x.iloc[8,:]).reshape(1,-1))

c:\Users\Amit\heroku-demos\heroku-env\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([3.])

In [19]:
np.array(test_x.iloc[8,:]).reshape(1,-1)

array([[15.       ,  0.       ,  0.       ,  1.       , 12.1905702,
        13.       ,  1.       ,  2.       ,  0.       ,  0.       ,
         0.       ,  0.       ]])

In [20]:
import sklearn
print(sklearn.__version__)

1.5.1


In [21]:
import numpy
print(numpy.__version__)

2.0.1


In [22]:
with open("classifer","wb") as file:
    pickle.dump(classifier,file)